# Generated by Django 5.0.1 on 2024-01-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='applied_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.TextField(default='No description available'),
        ),
    ]
