# Generated by Django 5.0.1 on 2024-01-19 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_rename_applied_at_job_created_at_job_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='resume',
        ),
    ]
